### ISSUE TITLE
你好。

### ISSUE THREAD

**Issue by ghost** [youkongling/exam-php#1]
我在学习小程序时候，也在做模拟一个考试系统，答案判断和界面样式等，就下载这个代码想做参考学习。这个代码是 Nodejs+express+ejs 实现的吗？  能否教一下怎么运行。

**Comment by youkongling** [comment]
是用node+express实现的，用node做的渲染，后台是用PHP做的，运行的话，直接npm install再npm start就行，本地调试就npm test
